import { Layout } from "@/components/layout";
import { QueryClient, TonConnectProvider } from "@/components/providers";
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO change
const MANIFEST_URL =
  "https://raw.githubusercontent.com/ton-community/tutorials/main/03-client/test/public/tonconnect-manifest.json";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <QueryClient>
          <TonConnectProvider manifestUrl={MANIFEST_URL}>
            <Layout>{children}</Layout>
          </TonConnectProvider>
        </QueryClient>
      </body>
    </html>
  );
}
